### ISSUE TITLE
Pyyaml version 6 update

### ISSUE THREAD

**Issue by AndrewW85** [Zuehlke/ConfZ#33]
With pyyaml being on version 6, would it be possible to get the major version either updated to 6 or unlocked from 5?

**Comment by silvanmelchior** [comment]
Yes, I'm currently on vacation, but I will update the version at the end of the month.

**Comment by AndrewW85** [comment]
Thanks, that would be awesome.  I'm submitting a PR, not that it is needed for a change this simple, but I might as well be the person who does the work I requested.

**Comment by silvanmelchior** [comment]
Yes of course, PRs are always welcome, also smaller ones.
