### ISSUE TITLE
How to populate optional sub-config from env-vars?

### ISSUE THREAD

**Issue by pumelo** [Zuehlke/ConfZ#42]
See this example:

```
import typing
from confz import ConfZ, ConfZEnvSource
from pydantic import SecretStr, AnyUrl
   
class S3Config(ConfZ):
    endpoint: AnyUrl
    bucket: str
    key: str
    secret: SecretStr


class AllConfig(ConfZ):

    primaryS3: typing.Optional[S3Config] = None
    secondaryS3: typing.Optional[S3Config] = None

    CONFIG_SOURCES = ConfZEnvSource(allow_all=True)
```

How can the `primaryS3.endpoint` be populated form env-vars? Using `primaryS3.endpoint` for the env-var will only work if `primaryS3` is not optional.  So I did not find a way to make this work .. Is this a case which is not yet supported?

**Comment by silvanmelchior** [comment]
Hi, I'm not sure if I can follow. In theory, this should be possible.

Can you maybe provide an example script where it works if `primaryS3` is not optional, but fails if it is optional? And the error you get?

**Comment by pumelo** [comment]
The issue was that I had uppercase letters in the variable name. As all variables from env are transformed to be lowercase it was not working.

Maybe you should highlite that in the docs or even raise an Exception if the configuration name contains an uppercase?

BTW: Thanks for providing this library on github 😃

**Comment by silvanmelchior** [comment]
Ok, yes, I think I've written it somewhere, but could for sure be more emphasized. A warning might probably not be worth the code-complexity (the ConfZSource would suddenly need to know that it's the only source and the config values, which it does not so far), but a better hint in the docs could prevent some mistakes here. I re-open the issue as a reminder.
