### ISSUE TITLE
Nested ConfZ configurations sourced from environment variables - resolving problems with variable names containing dots

### ISSUE THREAD

**Issue by vlcinsky** [Zuehlke/ConfZ#45]
**Goal**: Use env variables to set nested configuration values for an python application using `ConfZ` library.

File `tryit.py`:
```python
from confz import ConfZ, ConfZEnvSource


class UserSettings(ConfZ):
    username: str = "supervisor"
    password: str = "password"


class AppSettings(ConfZ):
    host: str = "localhost"
    port: int = 80
    admin: UserSettings = UserSettings()

    CONFIG_SOURCES = ConfZEnvSource(allow_all=True, prefix="APP_")


if __name__ == "__main__":
    """Following env variables allow modifying AppSettings:
    APP_HOST .. host name
    APP_PORT .. port number
    APP_ADMIN.USERNAME .. username
    APP_ADMIN.PASSWORD .. password
    """
    print(AppSettings())
```
Printing default configuration works well:

```shell
$ python tryit.py 
host='localhost' port=80 admin=UserSettings(username='supervisor', password='password')
```

Using env variable to change host name:

```shell
$ APP_HOST=RedDwarf python tryit.py 
host='RedDwarf' port=80 admin=UserSettings(username='supervisor', password='password')
```

Trying to use `APP_ADMIN.USERNAME` env variable to change admin username will fail as Bash shell do not allow dots in env variable names:

```shell
$ APP_HOST=RedDwarf APP_ADMIN.USERNAME=Dave python tryit.py 
bash: APP_ADMIN.USERNAME=Dave: command not found
```

But in general, Linux environment are not as strict as most shells so there are methods to set such variable, e.g. using `env`:

```bash
$ env APP_HOST=RedDwarf APP_ADMIN.USERNAME=Dave python tryit.py 
host='RedDwarf' port=80 admin=UserSettings(username='Dave', password='password')
```

<a id="org99f3f4a"></a>

# Particular findings

-   ConfZ allows nested configuraitons. When managing nested configuration parameters using env variables, their names do contain dot at the place of nesting.
-   Setting env variables having a dot in their name fails on most Linux shells (e.g. bash, sh) as they do not allow dots in variable names.
-   However, Linux environment in general allows names containing any character apart from `=` and `NUL`.
-   Command `env` allows setting environment variables even if they contain dots or other characters restricted by various shells.
-   Python process has no problem accessing values of environment variables regardless of their names.
-   ConfZ can read environment variables properly (as it is python process).
-   `ConfZEnvSource` allows loading environment variable values from `.env` files and there are no problems with dots in variable names.

<a id="org48df890"></a>

# Conclusions

`ConfZ` allows to define and manage nested configurations using environment variables and/or `.env` files. This functionality works from python application point of view without a problem.

To define value of a nested parameter, environment variable name contain dot character(s).

Trying to set value of an environment variable having a dot in its name might surprise in most Linux shells as those shells do not allow dots in names.

Solutions are easy:

- either define variables using `.env` files
- or use `env` command to define variable names.

**Comment by vlcinsky** [comment]
This is rather "how to" for documentation then real issue so feel free to close it.

**Comment by silvanmelchior** [comment]
Nice overview! Also interesting together with #44, which allows to change the separator.
