### ISSUE TITLE
Suggestion: file argument's type Path of ConfZSource should be reconsidered

### ISSUE THREAD

**Issue by Alyxion** [Zuehlke/ConfZ#61]
At the moment the **file** attribute of the **ConfZSource** class is enforced to be of type **Path**.

The **Path** type by itself has no positive impact for the user at all though and it's just annoying for the user of ConfZ to import the additional library **pathlib**.

Calling `CONFIG_SOURCES = ConfZFileSource(file=Path('!!$$123'))` is as valid until the actual loading of the config as of a valid file path at the moment.

Thus enforcing type **Path** should either be done consequent via early evaluation of the actual file path passed and/or (what i would prefer) file should be Union[Path,str] to avoid the effort of importing Path explicitly at every location where ConfZ is used.

```
from pathlib import Path

from confz import ConfZ, ConfZFileSource
from pydantic import SecretStr, AnyUrl

class DBConfig(ConfZ):
    user: str
    password: SecretStr

class APIConfig(ConfZ):
    host: AnyUrl
    port: int
    db: DBConfig

    CONFIG_SOURCES = ConfZFileSource(file=Path('/path/to/config.yml'))
```
-->

```
from confz import ConfZ, ConfZFileSource
from pydantic import SecretStr, AnyUrl

class DBConfig(ConfZ):
    user: str
    password: SecretStr

class APIConfig(ConfZ):
    host: AnyUrl
    port: int
    db: DBConfig

    CONFIG_SOURCES = ConfZFileSource(file='/path/to/config.yml')
```

**Comment by silvanmelchior** [comment]
Hi Mike, thanks for the feedback! I would be open for a PR to support all PEP 519-like paths (and corresponding tests), I agree that it would make the library more usable.

**Comment by Alyxion** [comment]
Great, will provide a PR within the next week.

**Comment by silvanmelchior** [comment]
Great!
