### ISSUE TITLE
How to handle hyphenated keynames in a toml file?

### ISSUE THREAD

**Issue by bmanturner** [Zuehlke/ConfZ#71]
For legacy reasons we have some hyphenated keynames in our config file. I have searched issues and documentation and can't find anything.

How might I go about this?

**Comment by silvanmelchior** [comment]
Hi, what config format do you use?

**Comment by bmanturner** [comment]
@silvanmelchior TOML. If that's not what you're asking, pardon my ignorance and please clarify.

**Comment by silvanmelchior** [comment]
Great!
