### ISSUE TITLE
Update python-dotenv pin to allow 1.0 release

### ISSUE THREAD

**Issue by alex-dr** [Zuehlke/ConfZ#72]
Python dotenv released `1.0.0`, and other packages are starting to pin to `>=1.0.0`, which ends up forcing pip to downgrade confz to an old release with a looser pin on dotenv.

The [changelog](https://github.com/theskumar/python-dotenv/compare/v0.21.1...v1.0.0) doesn't look too crazy, and in my own environment I haven't noticed any problems, so I suggest updating the pin to include at least the `1.0` versions.

**Comment by silvanmelchior** [comment]
Totally agree, comming soon

**Comment by silvanmelchior** [comment]
See release 1.8.2
