### ISSUE TITLE
Edit settings and save them to file

### ISSUE THREAD

**Issue by abrahammurciano** [Zuehlke/ConfZ#84]
Is there any way for me to, at runtime, update a setting and overwrite the value in the configuration file?

Even at least a way to reload the settings from source (not temporarily) if I know the sources have changed?

**Comment by silvanmelchior** [comment]
Hey, please see #83 regarding file update (short answer: no, so far not, would require quite some changes).

Regarding reloading, only if you use the non-singleton mechanism (passing the sources as keyword-arguments while instantiating a class)
